// Data-flow graph. 4 stages, nodes + edges + example schema. Refine freely.
// stage: 1 수집·연동 / 2 표준 저장(SoT) / 3 지표 산출(뷰) / 4 대시보드 화면
// schema rows: [field, type, example, tag]  ← tag = 출처 (see TAG_META in flow.js)
// node.tentative: 점선 표시(현재 미사용)

const FLOW_NODES = [
  // 1 — Ingest
  { id: "raw_listing", stage: 1, label: "raw_listing", sub: "리스팅 원천",
    desc: "TrustData가 직접 확보하는 원천 데이터. 글로벌 마켓플레이스(타오바오·티몰·1688·알리·쇼피·라자다 등)의 '의심 상품 1건'이 한 행. 데이터 벤더에서 구매(권장)하거나 크롤링으로 수집. 위조 여부·차단 결과 같은 운영 값은 아직 없음.",
    schema: [
      ["listing_id", "string", "TB-8843112905", "acquire"],
      ["product_name", "string", "코이셀로 가디건 여성 봄 신상", "6"],
      ["platform", "string", "Taobao", "6"],
      ["product_url", "string", "https://item.taobao.com/item.htm?id=8843112905", "6"],
      ["image_url", "string", "https://img.alicdn.com/i2/8843.jpg", "not-collected"],
      ["seller_name", "string", "inststudio设计师", "6"],
      ["price", "number", "325.00", "6"],
      ["currency", "string", "CNY", "derive"],
      ["sales_volume", "int", "1820", "6"],
      ["stock", "int", "10", "not-collected"],
      ["country", "string", "CN", "derive"],
      ["collected_at", "datetime", "2025-08-02T10:04:00Z", "acquire"],
    ] },
  { id: "raw_enforcement", stage: 1, label: "raw_enforcement", sub: "단속 결과(자체)",
    desc: "위조품 상태·차단 결과 등 TrustData가 자체 검증·단속 과정에서 직접 생성하는 값. 외부 피드가 아니라 대시보드 안에서 일하며 쌓이는 first-party 데이터. 화면 오른쪽 절반을 구동함.",
    schema: [
      ["listing_id", "string", "TB-8843112905", "firstparty"],
      ["status", "enum", "infringement", "firstparty"],
      ["priority", "enum", "high", "firstparty"],
      ["confirmation_date", "date", "2025-08-25", "firstparty"],
      ["closure_date", "date", "2025-11-17", "firstparty"],
      ["link_flag", "enum", "reactivated", "firstparty"],
      ["non_enforceable_reason", "enum|null", "null", "firstparty"],
      ["enforcement_outcome", "enum", "enforced", "firstparty"],
    ] },
  { id: "raw_seller", stage: 1, label: "raw_seller", sub: "셀러 프로필(선택)",
    desc: "리스팅 데이터 + TrustData의 과거 거래 기록에서 확보. 연락처류는 대부분 비어 있고, 개인정보 위험이 있어 설계상 제외 권장.",
    schema: [
      ["seller_name", "string", "inststudio设计师", "6"],
      ["seller_url", "string", "https://shop123.taobao.com", "acquire"],
      ["platform", "string", "Taobao", "6"],
      ["country", "string", "CN", "derive"],
      ["shop_open_date", "date", "2022-12-22", "acquire"],
      ["active", "bool", "true", "acquire"],
    ] },

  // 2 — Core
  { id: "incident", stage: 2, label: "incident", sub: "핵심 팩트",
    desc: "탐지된 링크 1건 = 1행. 확보한 리스팅과 자체 단속 결과가 합쳐져 정규화된, 모든 화면의 기준이 되는 단일 진실 원천.",
    schema: [
      ["id", "bigint", "1438606752", "acquire"],
      ["asset_id", "fk", "coyselo-tshirt", "classify"],
      ["platform_id", "fk", "taobao", "derive"],
      ["seller_id", "fk", "slr_00913", "firstparty"],
      ["protection_type", "enum", "product_counterfeit", "classify"],
      ["site_price", "number", "325.00", "6"],
      ["usd_price", "number", "45.73", "derive"],
      ["stock", "int", "9", "not-collected"],
      ["transactions", "int", "9", "6"],
      ["country", "string", "CN", "derive"],
      ["incident_status", "enum", "infringement", "firstparty"],
      ["incident_priority", "enum", "high", "firstparty"],
      ["detection_date", "date", "2025-08-02", "acquire"],
      ["confirmation_date", "date", "2025-08-25", "firstparty"],
      ["closure_date", "date", "2025-11-17", "firstparty"],
      ["link_flag", "enum|null", "reactivated", "firstparty"],
      ["non_enforceable_reason", "enum|null", "null", "firstparty"],
    ] },
  { id: "enforcement_event", stage: 2, label: "enforcement_event", sub: "상태 이벤트 로그",
    desc: "추가 전용(append-only) 이벤트: 모니터링→위조품 확정→차단완료/차단불가→재활성화. 대시보드가 운영 도구이므로 직원이 일할 때마다 실제 이벤트가 기록됨(재구성이 아니라 실제 기록). 모든 수치를 시점 기준으로 재현 가능하게 함.",
    schema: [
      ["event_id", "bigint", "99021", "firstparty"],
      ["incident_id", "fk", "1438606752", "firstparty"],
      ["event_type", "enum", "confirmed", "firstparty"],
      ["actor", "enum", "analyst", "firstparty"],
      ["occurred_at", "datetime", "2025-08-25T09:13:00Z", "firstparty"],
      ["note", "string|null", "null", "firstparty"],
    ] },
  { id: "seller", stage: 2, label: "seller", sub: "셀러",
    desc: "셀러 식별 단위. 셀러 이력이 first-party(자체 단속 이력)라 안정적 ID를 처음부터 부여 가능. 핸들을 바꿔 환생하는 교차계정 식별해소(ER)는 future.",
    schema: [
      ["id", "string", "slr_00913", "firstparty"],
      ["name", "string", "inststudio设计师", "6"],
      ["seller_url", "string", "https://shop123.taobao.com", "acquire"],
      ["platform", "string", "Taobao", "6"],
      ["country", "string", "CN", "derive"],
      ["active", "bool", "true", "firstparty"],
      ["is_official", "bool", "false", "customer"],
    ] },
  { id: "refdata", stage: 2, label: "asset · platform", sub: "기준정보",
    desc: "제품군(Asset)·플랫폼(Domain). 브랜드별로 달라지는 분류 체계.",
    schema: [
      ["asset.id", "string", "coyselo-tshirt", "classify"],
      ["asset.brand", "string", "Coyselo", "customer"],
      ["asset.name", "string", "Coyselo - T-Shirts", "classify"],
      ["platform.id", "string", "taobao", "derive"],
      ["platform.name", "string", "Taobao", "6"],
      ["platform.country", "string", "CN", "derive"],
    ] },
  { id: "lists", stage: 2, label: "allow / deny / watch", sub: "셀러 리스트",
    desc: "화이트리스트(공식 셀러는 신고 제외·표시)·차단·관찰 목록. TrustData가 관리.",
    schema: [
      ["list_type", "enum", "allow", "customer"],
      ["domain", "string", "item.taobao.com", "customer"],
      ["seller_name", "string", "coyselo.official", "customer"],
      ["added_by", "string", "customer", "customer"],
      ["added_at", "date", "2025-07-01", "customer"],
    ] },
  { id: "document", stage: 2, label: "document", sub: "국가별 IP 문서",
    desc: "브랜드 IP 등록증·수권서. 국가별 권리 → 단속 가능 여부 판단 근거. TrustData가 업로드·관리.",
    schema: [
      ["id", "string", "doc_kr_001", "customer"],
      ["brand", "string", "Coyselo", "customer"],
      ["country", "string", "KR", "customer"],
      ["doc_type", "enum", "trademark", "customer"],
      ["file_url", "string", "s3://docs/coyselo_kr_tm.pdf", "customer"],
      ["valid_until", "date", "2031-05-01", "customer"],
    ] },

  // 3 — Mart (views)
  { id: "v_incident", stage: 3, label: "v_incident", sub: "인시던트 뷰",
    desc: "조인·정규화된 인시던트(셀러/제품군/플랫폼 이름·한글 상태 라벨 포함). Validation·Database 화면 구동.",
    schema: [
      ["incident_id", "bigint", "1438606752", "acquire"],
      ["product_name", "string", "코이셀로 가디건 여성 봄", "6"],
      ["asset", "string", "Coyselo - T-Shirts", "classify"],
      ["platform", "string", "Taobao", "6"],
      ["seller", "string", "inststudio设计师", "6"],
      ["protection_type", "string", "상표침해/위조품", "classify"],
      ["usd_price", "number", "45.73", "derive"],
      ["stock", "int", "9", "not-collected"],
      ["status", "string", "위조품 확정", "firstparty"],
      ["detection_date", "date", "2025-08-02", "acquire"],
    ] },
  { id: "v_kpi", stage: 3, label: "v_kpi_summary", sub: "KPI 요약",
    desc: "Home·Summary 카드 지표. 누적+당월 두 윈도우. 차단성공률은 철회 제외 기준. 갱신 주기는 수집 주기에 따름.",
    schema: [
      ["period", "string", "2026-02", "derive"],
      ["monitoring", "int", "702", "acquire"],
      ["infringements", "int", "4891", "firstparty"],
      ["enforced", "int", "2948", "firstparty"],
      ["non_enforceable", "int", "476", "firstparty"],
      ["success_rate", "pct", "89.6", "derive"],
      ["covered_domains", "int", "85", "derive"],
    ] },
  { id: "v_economic", stage: 3, label: "v_economic_impact", sub: "경제적 가치",
    desc: "재고×가격 보수적 산정(미표시→1, 50 초과→50). 고객이 가장 중요시하는 지표인데, 핵심 입력 stock이 어떤 소스도 신뢰 불가(fuzzy) — 가치 최고/근거 최약, 항상 추정치.",
    schema: [
      ["total_value_usd", "number", "1768798.15", "derive"],
      ["total_units", "int", "127030", "not-collected"],
      ["total_transactions", "int", "5231", "6"],
      ["listings_removed", "int", "2969", "firstparty"],
      ["avg_price", "number", "17.41", "derive"],
      ["num_sellers", "int", "1488", "derive"],
    ] },
  { id: "v_seller_stats", stage: 3, label: "v_seller_stats", sub: "셀러 통계",
    desc: "셀러별 재집계·반복침해(180일 내 재침해) 등. 반복침해는 자체 단속 이력이 쌓여야 산출 — 운영하며 축적.",
    schema: [
      ["seller_id", "string", "slr_00913", "firstparty"],
      ["name", "string", "inststudio设计师", "6"],
      ["infringements", "int", "11", "firstparty"],
      ["enforced", "int", "5", "firstparty"],
      ["repeat_infringer", "bool", "true", "derive"],
      ["first_detected", "date", "2025-07-23", "acquire"],
    ] },
  { id: "v_nonenf", stage: 3, label: "v_non_enforceable", sub: "차단불가 집계",
    desc: "사유별·도메인별·링크별 차단불가 현황.",
    schema: [
      ["reason", "string", "Lack of IP rights", "firstparty"],
      ["domain", "string", "item.taobao.com", "derive"],
      ["country", "string", "CN", "derive"],
      ["count", "int", "365", "firstparty"],
    ] },
  { id: "v_top", stage: 3, label: "v_top_*", sub: "Top 집계",
    desc: "플랫폼·셀러·제품군·국가·침해유형별 Top-N 집계 + 드릴다운 진입점.",
    schema: [
      ["dimension", "enum", "platform", "derive"],
      ["key", "string", "AliExpress", "derive"],
      ["infringements", "int", "3226", "firstparty"],
      ["enforced", "int", "2061", "firstparty"],
    ] },
  { id: "v_evolution", stage: 3, label: "v_results_evolution", sub: "월별 추이",
    desc: "월별 위조품·차단완료 추이(꺾은선). 월별 스냅샷 보관 필요.",
    schema: [
      ["month", "string", "2025-09", "derive"],
      ["infringements", "int", "2592", "firstparty"],
      ["enforcements", "int", "1843", "firstparty"],
    ] },

  // 4 — Dashboard screens (no table schema — they read views)
  { id: "home", stage: 4, label: "Home", desc: "요약 KPI(funnel 스냅샷) + Top 플랫폼/셀러 드릴다운." },
  { id: "validation", stage: 4, label: "Validation", desc: "위조품 확정 운영 화면(확정/삭제/보류). 직원이 여기서 확정하면 enforcement_event로 기록됨 — 이 대시보드가 TrustData의 운영 도구임." },
  { id: "database", stage: 4, label: "Database", desc: "전체 데이터 필터 탐색(모든 상태·전기간 · 17개 필터)." },
  { id: "summary", stage: 4, label: "Summary", desc: "누적·월별 요약 그래프(시계열)." },
  { id: "analysis", stage: 4, label: "Result analysis", desc: "유형/제품군/플랫폼/셀러별 교차표. 일부 지표(정확도·노출률)는 Red Points 참조 디자인에서 온 것 — 자체 정의하거나 제외." },
  { id: "sellers", stage: 4, label: "Sellers", desc: "셀러별 분석(셀러 선택 시 전체 재집계). 이력 축적 필요." },
  { id: "economic", stage: 4, label: "Economic impact", desc: "경제적 가치 카드·월별·도메인/셀러/링크별. stock 미신뢰로 항상 추정." },
  { id: "nonenf", stage: 4, label: "Non-enforceable", desc: "차단불가 사유 현황." },
  { id: "config", stage: 4, label: "Configuration", desc: "셀러 리스트·IP 문서 관리(고객 관리 데이터)." },
];

const FLOW_EDGES = [
  ["raw_listing", "incident"], ["raw_listing", "seller"], ["raw_listing", "refdata"],
  ["raw_enforcement", "incident"], ["raw_enforcement", "enforcement_event"],
  ["raw_seller", "seller"],
  ["incident", "v_incident"], ["incident", "v_kpi"], ["incident", "v_economic"],
  ["incident", "v_top"], ["incident", "v_evolution"], ["incident", "v_nonenf"],
  ["enforcement_event", "v_kpi"], ["enforcement_event", "v_economic"], ["enforcement_event", "v_evolution"],
  ["seller", "v_seller_stats"], ["seller", "v_incident"],
  ["refdata", "v_incident"], ["refdata", "v_top"],
  ["lists", "v_incident"], ["document", "v_nonenf"],
  ["v_kpi", "home"], ["v_kpi", "summary"],
  ["v_top", "home"], ["v_top", "summary"], ["v_top", "analysis"],
  ["v_incident", "validation"], ["v_incident", "database"],
  ["v_economic", "economic"], ["v_seller_stats", "sellers"],
  ["v_nonenf", "nonenf"], ["v_evolution", "summary"],
  ["lists", "config"], ["document", "config"],
  ["validation", "enforcement_event", "writeback", "확정 기록"],
];

const STAGE_LABELS = {
  1: "① 수집 · 연동", 2: "② 표준 저장 (SoT)",
  3: "③ 지표 산출 (Views)", 4: "④ 대시보드 화면",
};
